.valid-branch:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - build
  - scan
  - publish

image-build:
  stage: build
  rules:
    - !reference [.valid-branch, rules]
  image: registry.bps.go.id/factory/aio-tools
  before_script:
    - echo "Logging into Gitlab Container Registry"
    - buildah login -u ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - echo "Login into Shared Container Registry"
    - buildah login -u ${SHARED_REGISTRY_USER} --password ${SHARED_REGISTRY_PASSWORD} ${SHARED_REGISTRY}
  script:
    - echo "Building ${CI_REGISTRY_IMAGE}"
    - buildah bud --tag ${CI_REGISTRY_IMAGE} --pull=newer ${KODERIA_BUILD_ARGS}
    - echo "Pushing ${CI_REGISTRY_IMAGE}"
    - buildah push ${CI_REGISTRY_IMAGE}

container_scanning:
  stage: scan
  variables:
    CS_IMAGE: ${CI_REGISTRY_IMAGE}
  rules:
    - !reference [.valid-branch, rules]
    
image-publish:
  rules:
    - !reference [.valid-branch, rules]
  image: registry.bps.go.id/factory/aio-tools
  stage: publish
  before_script:
    - echo "Login into Gitlab Container Registry"
    - skopeo login -u ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - echo "Login into Shared Container Registry"
    - skopeo login -u ${SHARED_REGISTRY_USER} --password ${SHARED_REGISTRY_PASSWORD} ${SHARED_REGISTRY}
  script:
    - skopeo copy docker://${CI_REGISTRY_IMAGE} docker://${SHARED_REGISTRY}/${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}
    - |
      curl -X POST \
      -H "Authorization: Bearer ${SHARED_REGISTRY_TOKEN}" \
      -H "Content-Type: application/json" \
      -d '{ "visibility": "public" }' \
      "https://${SHARED_REGISTRY}/api/v1/repository/${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}/changevisibility"