kind: Deployment
apiVersion: apps/v1
metadata:
  name: allstats-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allstats-hub
  template:
    metadata:
      labels:
        app: allstats-hub
        deployment: allstats-hub
    spec:
      imagePullSecrets:
        - name: devops-pull
      containers:
        - name: allstats-hub
          # Image is dynamically set by CI using `kustomize edit set image`
          image: devops-registry.bps.go.id/dpeps/allstats-hub
          envFrom:
            - secretRef:
                name: env-allstats-hub
          ports:
            - containerPort: 8080
              protocol: TCP
