kind: Service
apiVersion: v1
metadata:
  name: allstats-hub
spec:
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  selector:
    app: allstats-hub
    deployment: allstats-hub
