.valid-branch:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /.*hotfix.*/'  # Matches branches starting with 'hotfix/'
      when: always
    - if: $CI_COMMIT_BRANCH == "development"
      when: always
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

.release-job:
  needs: ["get-version"]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  variables:
    CI_SERVER_URL: https://$CI_SERVER_HOST
  script:
    - echo "running release_job for $VERSION"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v$VERSION'
    name: 'Release v$VERSION'
    description: 'Release created using the release-cli.'

.bump-gitops:
  needs: ["get-version"]
  variables:
    APP: $CI_PROJECT_NAME
    VERSION: $VERSION
  trigger:
    project: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAMESPACE}-gitops
    strategy: depend