kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: allstats-hub
  annotations:
    haproxy.router.openshift.io/timeout: "300s"
spec:
  to:
    kind: Service
    name: allstats-hub
    weight: 100
  port:
    targetPort: 80-tcp
  wildcardPolicy: None
  host: allstats-hub-dev.apps.bps.go.id
