kind: Deployment
apiVersion: apps/v1
metadata:
  name: allstats-hub-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allstats-hub-worker
  template:
    metadata:
      labels:
        app: allstats-hub-worker
        deployment: allstats-hub-worker
    spec:
      imagePullSecrets:
        - name: devops-pull
      containers:
        - name: allstats-hub-worker
          image: devops-registry.bps.go.id/dpeps/allstats-backend
          command: ["npm", "run", "start", "--", "--hostname", "0.0.0.0"]
          envFrom:
            - secretRef:
                name: env-allstats-hub
